const data = [
  {
    id: 1,
    image: "./card-1.png",
    title: "lugx-gaming",
    category: "react",
    live: "https://fares-sonar.github.io/lugx-gaming/",
    git: "https://github.com/fares-sonar/lugx-gaming.git",
  },
  {
    id: 2,
    image: "./card-2.png",
    title: "Interior-Design",
    category: "html",
    live: "https://fares-sonar.github.io/Interior-Design/",
    git: "https://github.com/fares-sonar/Interior-Design.git",
  },
  {
    id: 3,
    image: "./card-4.png",
    title: "Shopping-Cart",
    category: "javascript",
    live: "https://fares-sonar.github.io/Add-Shoping-Cart/",
    git: "https://github.com/fares-sonar/Add-Shoping-Cart",
  },
  {
    id: 4,
    image: "./card-5.png",
    title: "Villa-Agency",
    category: "react",
    live: "https://fares-sonar.github.io/Villa-Agency/",
    git: "https://github.com/fares-sonar/Villa-Agency.git",
  },
  {
    id: 5,
    image: "./card-8.png",
    title: "Image-gallery",
    category: "javascript",
    live: "https://fares-sonar.github.io/Image-gallery/",
    git: "https://github.com/fares-sonar/Image-gallery.git",
  },
  {
    id: 6,
    image: "./card-3.png",
    title: "landing page",
    category: "html",
    live: "https://fares-sonar.github.io/landing-page/",
    git: "https://github.com/fares-sonar/landing-page.git",
  },
  {
    id: 7,
    image: "./card-6.png",
    title: "Christmas_design",
    category: "html",
    live: "https://fares-sonar.github.io/Christmas_desigin/",
    git: "https://github.com/fares-sonar/Christmas_desigin.git",
  },
  {
    id: 8,
    image: "./card-7.png",
    title: "fitness-website",
    category: "html",
    live: "https://fares-sonar.github.io/fitness-website/",
    git: "https://github.com/fares-sonar/fitness-website.git",
  },
];
export default data;
